import { useState, useEffect, useRef } from 'react';
import { 
    PhoneCall, Mic, MicOff, PhoneOff, CheckSquare, X, Download, Save, 
    History, Plus, User, Sparkles, Zap, ExternalLink 
} from 'lucide-react';
import { useToast } from '../hooks/useToast';
import { dialerEvents } from '../constants/events';
import { leadsApi } from '../api/client';

// Expose trigger for demo/debug globally
window.simulateInbound = () => {
    dialerEvents.triggerInbound('L001', '9000077665', 'Ishaan Taneja', {
        lastInquiry: 'Marvel Bosque (3BHK)',
        leadScore: 88
    });
};

export default function Dialer() {
    const { showToast } = useToast();
    const [activeCall, setActiveCall] = useState(null);
    const [incomingCall, setIncomingCall] = useState(null);
    const [status, setStatus] = useState('idle'); // idle, ringing, connected
    const [timer, setTimer] = useState(0);
    const [muted, setMuted] = useState(false);
    const [showNotes, setShowNotes] = useState(false);
    const [notes, setNotes] = useState('');
    const [saving, setSaving] = useState(false);
    const timerRef = useRef(null);

    useEffect(() => {
        const handleCall = (data) => {
            if (data.isInbound) {
                setIncomingCall(data);
                return;
            }
            setActiveCall(data);
            setStatus('ringing');
            setTimer(0);
            setMuted(false);
            setShowNotes(false);
            setNotes('');
            showToast(`Dialing ${data.name}...`, 'info');

            // Simulate pickup after 2 seconds
            setTimeout(() => {
                setStatus('connected');
                showToast(`Call connected with ${data.name}`, 'success');
            }, 2000);
        };

        dialerEvents.subscribe(handleCall);
        return () => dialerEvents.unsubscribe(handleCall);
    }, [showToast]);

    useEffect(() => {
        if (status === 'connected') {
            timerRef.current = setInterval(() => setTimer(t => t + 1), 1000);
        } else {
            clearInterval(timerRef.current);
        }
        return () => clearInterval(timerRef.current);
    }, [status]);

    const formatTime = (secs) => {
        const m = Math.floor(secs / 60);
        const s = secs % 60;
        return `${m}:${s.toString().padStart(2, '0')}`;
    };

    const handleHangup = async () => {
        if (status === 'connected' && activeCall?.id) {
            setSaving(true);
            try {
                await leadsApi.addInteraction(activeCall.id, {
                    type: 'Call',
                    date: new Date(),
                    duration: formatTime(timer),
                    note: notes || 'Outbound call completed.',
                    outcome: 'Connected'
                });
                showToast('Call logged successfully to lead history.', 'success');
            } catch (err) {
                console.error(err);
                showToast('Call ended, but failed to log to history.', 'error');
            } finally {
                setSaving(false);
            }
        } else {
            showToast('Call ended.', 'info');
        }

        setActiveCall(null);
        setStatus('idle');
        setTimer(0);
    };

    const exportCallLog = () => {
        const logContent = `
ZENTRIX CRM - CALL RECORD
-------------------------
Lead Name: ${activeCall.name}
Phone Number: ${activeCall.number}
Date: ${new Date().toLocaleString()}
Duration: ${formatTime(timer)}
Status: ${status}
Notes: ${notes || 'No notes provided.'}
-------------------------
Generated by Zentrix CRM
        `.trim();

        const blob = new Blob([logContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `call_log_${activeCall.name.replace(/\s+/g, '_')}_${Date.now()}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        showToast('Call record exported to your local file.', 'success');
    };

    const handleAccept = () => {
        setActiveCall(incomingCall);
        setStatus('connected');
        setIncomingCall(null);
        setTimer(0);
        showToast(`Call accepted from ${incomingCall.name}`, 'success');
    };

    const handleReject = () => {
        setIncomingCall(null);
        showToast('Inbound call rejected.', 'info');
    };

    if (!activeCall && !incomingCall) return null;

    if (incomingCall) {
        return (
            <div style={{
                position: 'fixed', top: 40, right: 40, zIndex: 10000, width: 440,
                background: '#0a1a2e', color: 'white', borderRadius: 28, padding: '32px',
                boxShadow: '0 30px 90px rgba(0,0,0,0.5)', border: '1px solid rgba(255,255,255,0.08)',
                fontFamily: 'var(--font-main)',
                animation: 'slideInRight 0.5s cubic-bezier(0.16, 1, 0.3, 1)'
            }}>
                {/* Header Section */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 28 }}>
                    <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
                        <div style={{ position: 'relative' }}>
                            <div style={{ 
                                width: 84, height: 84, borderRadius: '24px', background: 'white', 
                                display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0a1a2e' 
                            }}>
                                <User size={40} strokeWidth={2.5} />
                            </div>
                            <div style={{ 
                                position: 'absolute', bottom: 6, right: 6, width: 20, height: 20, 
                                borderRadius: '50%', background: '#10b981', border: '4px solid #0a1a2e',
                                animation: 'pulse-dot 2s infinite'
                            }} />
                        </div>
                        <div>
                            <div style={{ fontSize: '12px', fontWeight: 900, color: '#38bdf8', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>Inbound Call via IVR</div>
                            <div style={{ fontSize: '28px', fontWeight: 900, marginBottom: 4, letterSpacing: '-0.02em' }}>{incomingCall.name}</div>
                            <div style={{ fontSize: '15px', color: '#94a3b8', fontWeight: 600 }}>{incomingCall.number}</div>
                        </div>
                    </div>
                    <button onClick={handleReject} style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', padding: 4 }} className="hover-lift">
                        <X size={24} />
                    </button>
                </div>

                {/* AI Match Section */}
                <div style={{ 
                    padding: '24px', background: 'rgba(255,255,255,0.04)', borderRadius: 24, 
                    marginBottom: 32, border: '1px solid rgba(255,255,255,0.08)' 
                }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
                        <Zap size={16} color="#f59e0b" fill="#f59e0b" />
                        <span style={{ fontSize: '13px', fontWeight: 900, color: 'white', letterSpacing: '0.02em' }}>AI Instant Match</span>
                    </div>
                    
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, marginBottom: 20 }}>
                        <div>
                            <div style={{ fontSize: '10px', fontWeight: 800, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>Last Inquiry</div>
                            <div style={{ fontSize: '15px', fontWeight: 800 }}>{incomingCall.lastInquiry || 'N/A'}</div>
                        </div>
                        <div>
                            <div style={{ fontSize: '10px', fontWeight: 800, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>Lead Score</div>
                            <div style={{ fontSize: '15px', fontWeight: 900, color: '#10b981' }}>{incomingCall.leadScore || 0}/100</div>
                        </div>
                    </div>

                    <div style={{ display: 'flex', gap: 16 }}>
                        <button style={{ 
                            background: 'none', border: 'none', color: '#38bdf8', fontSize: '13px', 
                            fontWeight: 800, display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' 
                        }} className="hover-lift">
                            <ExternalLink size={14} /> Full Profile
                        </button>
                        <button style={{ 
                            background: 'none', border: 'none', color: '#94a3b8', fontSize: '13px', 
                            fontWeight: 800, display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' 
                        }} className="hover-lift">
                            <History size={14} /> History
                        </button>
                    </div>
                </div>

                {/* Actions */}
                <div style={{ display: 'flex', gap: 16 }}>
                    <button onClick={handleAccept} style={{ 
                        flex: 1, height: 64, borderRadius: 20, background: '#10b981', color: 'white', 
                        border: 'none', fontWeight: 900, fontSize: '18px', display: 'flex', alignItems: 'center', 
                        justifyContent: 'center', gap: 12, cursor: 'pointer', transition: 'all 0.2s', 
                        boxShadow: '0 10px 30px rgba(16,185,129,0.3)'
                    }} className="hover-lift">
                        <PhoneCall size={24} fill="currentColor" /> Accept
                    </button>
                    <button onClick={handleReject} style={{ 
                        width: 64, height: 64, borderRadius: 20, background: '#f43f5e', color: 'white', 
                        border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', 
                        cursor: 'pointer', transition: 'all 0.2s', boxShadow: '0 10px 30px rgba(244,63,94,0.3)'
                    }} className="hover-lift">
                        <PhoneOff size={24} />
                    </button>
                </div>

                <style>{`
                    @keyframes slideInRight {
                        from { transform: translateX(500px); opacity: 0; }
                        to { transform: translateX(0); opacity: 1; }
                    }
                    @keyframes pulse-dot {
                        0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.7); }
                        70% { transform: scale(1); box-shadow: 0 0 0 10px rgba(16, 185, 129, 0); }
                        100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(16, 185, 129, 0); }
                    }
                `}</style>
            </div>
        );
    }

    return (
        <div style={{
            position: 'fixed', bottom: 40, right: 40, zIndex: 9999, width: 360,
            background: 'white', borderRadius: 24, boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)',
            border: '1px solid #dfe3eb', overflow: 'hidden', animation: 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)'
        }}>
            {/* HubSpot Theme Header */}
            <div style={{
                background: status === 'connected' ? '#00a38d' : '#33475b',
                color: 'white', padding: '24px', textAlign: 'center', transition: 'background 0.3s'
            }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '11px', fontWeight: 800, background: 'rgba(255,255,255,0.15)', padding: '4px 10px', borderRadius: 20, letterSpacing: '0.05em' }}>
                        <History size={12} /> {status === 'ringing' ? 'DIALING...' : 'LIVE CALL'}
                    </div>
                    <button onClick={handleHangup} style={{ background: 'transparent', border: 'none', color: 'rgba(255,255,255,0.7)', cursor: 'pointer', padding: 4 }} onMouseEnter={e => e.currentTarget.style.color = 'white'} onMouseLeave={e => e.currentTarget.style.color = 'rgba(255,255,255,0.7)'}>
                        <X size={20} />
                    </button>
                </div>

                <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'rgba(255,255,255,0.2)', border: '2px solid rgba(255,255,255,0.3)', margin: '0 auto 16px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '28px', fontWeight: 800 }}>
                    {activeCall.name.split(' ').map(n => n[0]).join('')}
                </div>

                <h3 style={{ fontSize: '1.5rem', fontWeight: 700, margin: '0 0 4px', letterSpacing: '-0.01em' }}>{activeCall.name}</h3>
                <div style={{ fontSize: '14px', color: 'rgba(255,255,255,0.9)', fontWeight: 500, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6 }}>
                    {activeCall.number}
                </div>
                <div style={{ marginTop: 12, fontSize: '18px', fontWeight: 700, fontFamily: 'monospace', color: '#ffea00' }}>
                    {status === 'ringing' ? (
                        <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                            <PhoneCall size={18} className="animate-pulse" /> Connecting...
                        </span>
                    ) : formatTime(timer)}
                </div>
            </div>

            {/* Main Action Area */}
            <div style={{ padding: '32px 24px' }}>
                <div style={{ display: 'flex', justifyContent: 'center', gap: 20, marginBottom: 32 }}>
                    <button
                        onClick={() => setMuted(!muted)}
                        title={muted ? 'Unmute' : 'Mute'}
                        style={{
                            width: 56, height: 56, borderRadius: '50%', border: '1px solid #cbd6e2', cursor: 'pointer',
                            background: muted ? '#fef2f2' : 'white',
                            color: muted ? '#ef4444' : '#516f90',
                            display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s',
                            boxShadow: muted ? 'inset 0 2px 4px rgba(0,0,0,0.05)' : '0 2px 4px rgba(0,0,0,0.05)'
                        }}
                    >
                        {muted ? <MicOff size={24} /> : <Mic size={24} />}
                    </button>

                    <button
                        onClick={handleHangup}
                        disabled={saving}
                        style={{
                            width: 72, height: 72, borderRadius: '50%', border: 'none', cursor: 'pointer',
                            background: '#ff5c35', color: 'white', boxShadow: '0 10px 20px rgba(255,92,53,0.3)',
                            display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s',
                            transform: saving ? 'scale(0.9)' : 'scale(1)'
                        }}
                    >
                        <PhoneOff size={32} />
                    </button>

                    <button
                        onClick={() => setShowNotes(!showNotes)}
                        title="Add Call Notes"
                        style={{
                            width: 56, height: 56, borderRadius: '50%', border: '1px solid #cbd6e2', cursor: 'pointer',
                            background: showNotes ? '#f5f8fa' : 'white',
                            color: showNotes ? '#0091ae' : '#516f90',
                            display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'all 0.2s',
                            boxShadow: showNotes ? 'inset 0 2px 4px rgba(0,0,0,0.05)' : '0 2px 4px rgba(0,0,0,0.05)'
                        }}
                    >
                        <CheckSquare size={24} />
                    </button>
                </div>

                {/* Notes Input */}
                <div style={{ transition: 'all 0.3s' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                        <span style={{ fontSize: '13px', fontWeight: 800, color: '#33475b', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Call Notes</span>
                        <div style={{ display: 'flex', gap: 8 }}>
                            <button onClick={exportCallLog} style={{ background: 'none', border: 'none', color: '#0091ae', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4, fontSize: '12px', fontWeight: 700 }}>
                                <Download size={14} /> Export File
                            </button>
                        </div>
                    </div>
                    <textarea
                        value={notes}
                        onChange={(e) => setNotes(e.target.value)}
                        placeholder="Detail the outcome of this conversation..."
                        style={{
                            width: '100%', height: 100, padding: '12px 16px', borderRadius: 12,
                            border: '1px solid #cbd6e2', background: '#f5f8fa',
                            resize: 'none', fontSize: '14px', fontFamily: 'inherit',
                            color: '#33475b', outline: 'none', focus: { borderColor: '#0091ae' }
                        }}
                    />
                </div>

                <div style={{ marginTop: 24, fontSize: '12px', color: '#516f90', textAlign: 'center', borderTop: '1px solid #dfe3eb', paddingTop: 16 }}>
                    Calls are automatically logged and saved locally for your records.
                </div>
            </div>

            <style>{`
                @keyframes slideUp {
                    from { transform: translateY(100px); opacity: 0; }
                    to { transform: translateY(0); opacity: 1; }
                }
                @keyframes pulse {
                    0% { transform: scale(1); opacity: 1; }
                    50% { transform: scale(1.5); opacity: 0.5; }
                    100% { transform: scale(1); opacity: 1; }
                }
                .animate-pulse { animation: pulse 2s infinite; }
            `}</style>
        </div>
    );
}
